#:schema node_modules/wrangler/config-schema.json
name = "forex-experts-website"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB" # Environment variable name
database_name = "forex-experts-db" # Production database name
database_id = "your-production-database-id" # Replace with actual production ID after creation
preview_database_id = "forex-experts-db-preview" # Preview database ID

[[d1_databases]]
binding = "DB" # Local development binding
database_name = "forex-experts-db-local"
database_id = "local-db-forex-experts"
